Import('env', 'plugins')

plugins += env.SharedLibrary('isotropic', ['isotropic.cpp'])
plugins += env.SharedLibrary('hg', ['hg.cpp'])
plugins += env.SharedLibrary('rayleigh', ['rayleigh.cpp'])
plugins += env.SharedLibrary('kkay', ['kkay.cpp'])
plugins += env.SharedLibrary('microflake', ['microflake.cpp'])
plugins += env.SharedLibrary('mixturephase', ['mixturephase.cpp'])
plugins += env.SharedLibrary('forward_gaussian', ['forward_gaussian.cpp'])
plugins += env.SharedLibrary('fwddip_helper', ['fwddip_helper.cpp'])

Export('plugins')
