Import('env', 'plugins')

plugins += env.SharedLibrary('obj', ['obj.cpp'])
# TODO: ply plugin has compile error (name collision with newer boost libs?)
#plugins += env.SharedLibrary('ply', ['ply.cpp', 'ply/ply_parser.cpp'],
#   CPPPATH = env['CPPPATH'] + ['#src/shapes'])
plugins += env.SharedLibrary('serialized', ['serialized.cpp'])
plugins += env.SharedLibrary('rectangle', ['rectangle.cpp'])
plugins += env.SharedLibrary('disk', ['disk.cpp'])
plugins += env.SharedLibrary('sphere', ['sphere.cpp'])
plugins += env.SharedLibrary('cylinder', ['cylinder.cpp'])
plugins += env.SharedLibrary('hair', ['hair.cpp'])
plugins += env.SharedLibrary('shapegroup', ['shapegroup.cpp'])
plugins += env.SharedLibrary('instance', ['instance.cpp'])
plugins += env.SharedLibrary('cube', ['cube.cpp'])
plugins += env.SharedLibrary('heightfield', ['heightfield.cpp'])
#plugins += env.SharedLibrary('deformable', ['deformable.cpp'])

Export('plugins')
